kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile-n1
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-n1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile-n1
  resources:
    requests:
      storage: 5Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile-n2
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-azurefile-n2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-azurefile-n2
  resources:
    requests:
      storage: 5Gi
---