apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-s1
  namespace: ratingsapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: ratingsapp
    shareName: aksshare0404 
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
