apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-s1
  namespace: ratingsapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
